### ISSUE TITLE
Lost connect every restart server

### ISSUE THREAD

**Issue by XenonRaite** [UnwrittenFun/ImmersiveIntegration#70]
Hi!
I play on kcaldron 1614.

Every time restart server, my AE system lost connect with other devices located behind wires.

i see in code and found problem...
I used wirless terminal, soo i have setup security.

`[02:18:10] [Server thread/INFO] [immersiveintegration/]: Connect fail:null
[02:18:10] [Server thread/WARN] [/]: appeng.api.exceptions.FailedConnection
[02:18:10] [Server thread/WARN] [/]:    at appeng.me.GridConnection.<init>(GridConnection.java:70)
[02:18:10] [Server thread/WARN] [/]:    at appeng.core.Api.createGridConnection(Api.java:132)
[02:18:10] [Server thread/WARN] [/]:    at unwrittenfun.minecraft.immersiveintegration.tiles.TileMETransformer.connectTo(TileMETransformer.java:243)
[02:18:10] [Server thread/WARN] [/]:    at unwrittenfun.minecraft.immersiveintegration.tiles.TileMETransformer.func_145845_h(TileMETransformer.java:72)
[02:18:10] [Server thread/WARN] [/]:    at net.minecraft.world.World.func_72939_s(World.java:2529)
[02:18:10] [Server thread/WARN] [/]:    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
[02:18:10] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
[02:18:10] [Server thread/WARN] [/]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[02:18:10] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[02:18:10] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[02:18:10] [Server thread/WARN] [/]:    at java.lang.Thread.run(Unknown Source)`

it is hapen becose.

`[02:18:10] [Server thread/INFO] [/]: [IIDEBUG]:Platform.securityCheck( a, b )=true
[02:18:10] [Server thread/INFO] [/]: [IIDEBUG]:lastSecurityKey nodeA-1
[02:18:10] [Server thread/INFO] [/]: [IIDEBUG]:lastSecurityKey nodeB14524518844029`

but i no have idea why it`s hapen =(

**Comment by XenonRaite** [comment]
i added:
`((GridNode)nodeA).lastSecurityKey = -1;
((GridNode)nodeB).lastSecurityKey = -1;`

To TileMEWireConnector & TileMETransformer in connectTo method and it`s helped.
